[package]
name = "chunkee-godot"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.3.5"
chunkee-core = { path = "../../chunkee-core" }
noise = "0.9.0"
dashmap = "6.1.0"
env_logger = "0.11.8"
once_cell = "1.21.3"
